image: altmattr/simulation:latest

ports:
  - port: 8090
    visibility: public
    onOpen: open-browser
  - port: 4000-88000
    visibility: public
    onOpen: ignore

tasks:
  - name: Start Server
    command: |
      pip install flask
      export FLASK_APP=/home/developer/html/server.py
      python3 -m flask run --host=0.0.0.0 --port=8090 &
      gp preview `gp url 8090`/hud-min
  - name: Start Simulation
    command: |
      source /home/developer/vrx_ws/devel/setup.bash
      roslaunch rosbridge_server rosbridge_websocket.launch port:=9090 &
      rosrun web_video_server web_video_server _port:=8091 & 
  - name: Node Playground
    command: |
      npm install three axios roslib @tensorflow/tfjs