networks:
  ros-network:
    driver: bridge
    name: ros-network

services:
  master:
    build: ./images/master
    container_name: master
    hostname: master # allows communication by name between containers
    image: master
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
    ports:
      - 11311:11311
      - 9090:9090
  logic_python:
    build: ./images/logic_python
    container_name: logic_python
    hostname: logic_python # allows communication by name between containers
    image: logic_python
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
  logic_ocaml:
    build: ./images/logic_ocaml
    container_name: logic_ocaml
    hostname: logic_ocaml
    image: logic_ocaml
    networks:
      - ros-network
    volumes:
      - ./local_programs/ocaml_coq_extraction:/home/opam/thruster_allocation
    stdin_open: true
    tty: true
  simulation:
    build: ./images/sim
    container_name: sim
    hostname: sim
    image: simulation
    networks:
      - ros-network
