networks:
  ros-network:
    driver: bridge
    name: ros-network

services:
  master:
    build: ./images/master
    container_name: master
    hostname: master # allows communication by name between containers
    image: master
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
  logic_python:
    build: ./images/logic_python
    container_name: logic_python
    hostname: logic_python
    image: logic_python
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
