networks:
  ros-network:
    driver: bridge
    name: ros-network
services:
  master:
    build: ./images/master
    container_name: master
    hostname: master # allows communication by name between containers
    image: master
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
    ports:
      - 11311:11311
      - 9090:9090    # allows host application to talk to master
    environment:
      - ROS_MASTER_URI=http://master:11311
  logic_python:
    build: ./images/logic_python
    container_name: logic_python
    hostname: logic_python # allows communication by name between containers
    image: logic_python
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
  logic_hasekll:
    build: ./images/logic_haskell
    container_name: logic_haskell
    hostname: logic_haskell
    image: logic_haskell
    networks:
      - ros-network
    volumes:
      - ./local_programs/haskell_coq_extraction:/home/thruster_allocation
    stdin_open: true
    tty: true
  simulation:
    build: ./images/sim
    container_name: sim
    hostname: sim
    image: simulation
    runtime: nvidia
    networks:
      - ros-network
    stdin_open: true # -i
    tty: true        # -t
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
    ports:
      - 11311:11311
      - 9090:9090    # allows host application to talk to master
